spring.application.name=knowledge-os

spring.datasource.url=jdbc:mysql://localhost:3306/knowledge_os
spring.datasource.username=YOUR_USENAME
spring.datasource.password=YOUR_MYSQL_PASSWORD

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

chroma.base-url=http://127.0.0.1:8000
chroma.collection.name=knowledge_documents

ollama.embedding.model=nomic-embed-text
rag.top-k=5
rag.chunk-size=1000
rag.chunk-overlap=150
rag.max-extraction-length=15000

server.port=8080
spring.thymeleaf.cache=false